### ISSUE TITLE
Tencent WeChat Internation IP

### ISSUE THREAD

**Issue by kurikomoe** [dler-io/Rules#36]
受影响分流：
# > Tencent WeChat (International)
IP-CIDR,101.32.96.0/20,DIRECT,no-resolve
IP-CIDR,101.32.104.0/21,DIRECT,no-resolve
IP-CIDR,101.32.118.0/23,DIRECT,no-resolve
IP-CIDR,129.226.0.0/16,DIRECT,no-resolve
IP-CIDR,183.128.0.0/11,DIRECT,no-resolve
IP-CIDR,183.131.48.0/20,DIRECT,no-resolve

其中，101.32 相关 ip 在北京电信移动网络无法连接（2023/3/22 测试）
建议将 WeChat（非微信） 相关 ip 移出国内列表。

**Comment by pickrui** [comment]
Done.
